
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 11;
  public static final int BOX = 7;
  public static final int SATIS = 4;
  public static final int NOM = 13;
  public static final int RPARAN = 3;
  public static final int LPARAN = 2;
  public static final int EOF = 0;
  public static final int DIA = 6;
  public static final int IMP = 8;
  public static final int error = 1;
  public static final int NOT = 10;
  public static final int BIIMP = 9;
  public static final int OR = 12;
  public static final int PROP = 14;
  public static final int E = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPARAN",
  "RPARAN",
  "SATIS",
  "E",
  "DIA",
  "BOX",
  "IMP",
  "BIIMP",
  "NOT",
  "AND",
  "OR",
  "NOM",
  "PROP"
  };
}

